version: "3.9"

services:
  # =========================
  # DATABASES
  # =========================
  # postgres:
  #   image: postgres:16
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: app_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # mysql:
  #   image: mysql:8.3
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: app_db
  #     MYSQL_USER: app_user
  #     MYSQL_PASSWORD: app_pass
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # mongo:
  #   image: mongo:7
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  # =========================
  # CACHE / MESSAGE BROKERS
  # =========================
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # kafka:
  #   image: bitnami/kafka:3.7.0
  #   container_name: kafka
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_CFG_NODE_ID=0
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #   volumes:
  #     - kafka_data:/bitnami/kafka

  # zookeeper:
  #   image: bitnami/zookeeper:3.9.2
  #   container_name: zookeeper
  #   restart: always
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   volumes:
  #     - zookeeper_data:/bitnami/zookeeper

  # =========================
  # OPTIONAL - ADMIN TOOLS
  # =========================
  # pgadmin:
  #   image: dpage/pgadmin4:8
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  #   depends_on:
  #     - kafka
  #     - zookeeper

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "8005:8001"
    depends_on:
      - redis

volumes:
  # postgres_data:
  # mysql_data:
  # mongo_data:
  redis_data:
  # kafka_data:
  # zookeeper_data:
