server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120

database:
  host: "localhost"
  port: "3306"
  user: "nakku"
  password: "nakkupassword"
  name: "nakku"
  ssl_mode: "disable"
  max_conns: 25
  min_conns: 5

kafka:
  brokers:
    - "localhost:9092"
  group_id: "nakku-group"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "nakku-secret-key-change-in-production"
  expiration: 3600

log:
  level: "info"
  format: "json"
